// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('./components/Accordion.vue')['default']
    BurgerModal: typeof import('./components/BurgerModal.vue')['default']
    CarbonBareMetalServer: typeof import('~icons/carbon/bare-metal-server')['default']
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonChevronDown: typeof import('~icons/carbon/chevron-down')['default']
    CarbonChevronSortDown: typeof import('~icons/carbon/chevron-sort-down')['default']
    CarbonChevronUp: typeof import('~icons/carbon/chevron-up')['default']
    CarbonClose: typeof import('~icons/carbon/close')['default']
    CarbonDevices: typeof import('~icons/carbon/devices')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonFaceSatisfied: typeof import('~icons/carbon/face-satisfied')['default']
    CarbonHome: typeof import('~icons/carbon/home')['default']
    CarbonHouse: typeof import('~icons/carbon/house')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLaptop: typeof import('~icons/carbon/laptop')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMenu: typeof import('~icons/carbon/menu')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonPedestrian: typeof import('~icons/carbon/pedestrian')['default']
    CarbonQuery: typeof import('~icons/carbon/query')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonTwoPersonLift: typeof import('~icons/carbon/two-person-lift')['default']
    CarbonUserAdmin: typeof import('~icons/carbon/user-admin')['default']
    CarbonUserFavorite: typeof import('~icons/carbon/user-favorite')['default']
    CarbonVolumeCostCard: typeof import('~icons/carbon/volume-cost-card')['default']
    CarbonVolumeFileCard: typeof import('~icons/carbon/volume-file-card')['default']
    CarbonVolumeFileStorage: typeof import('~icons/carbon/volume-file-storage')['default']
    CarbonVolumeFileStoragerd: typeof import('~icons/carbon/volume-file-storagerd')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    CostCard: typeof import('./components/CostCard.vue')['default']
    CostSplash: typeof import('./components/CostSplash.vue')['default']
    FaqSplash: typeof import('./components/FaqSplash.vue')['default']
    FaqsSplash: typeof import('~icons/fa/qs-splash')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    HomeSplash: typeof import('./components/HomeSplash.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    NavbarItem: typeof import('./components/NavbarItem.vue')['default']
    README: typeof import('./components/README.md')['default']
    Splash: typeof import('./components/HomeSplash.vue')['default']
    WhatWeDo: typeof import('./components/WhatWeDo.vue')['default']
  }
}

export { }
